In [1]:
import numpy as np
a = np.array([1,2,4,6])
Y=4
np.vander(a,Y)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 64,  16,   4,   1],
       [216,  36,   6,   1]])

In [2]:
np.column_stack([a**(Y-1-i) for i in range(Y)])

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 64,  16,   4,   1],
       [216,  36,   6,   1]], dtype=int32)

In [4]:
import numpy as np
a = np.array([1,2,4,5])
np.vander(a)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 64,  16,   4,   1],
       [125,  25,   5,   1]])

In [5]:
np.vander(a, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   4,  16,  64],
       [  1,   5,  25, 125]])

In [7]:
import numpy as np
def moving_average(a, n=3):
    asum = np.cumsum(a, dtype=float)
    asum[n:] = asum[n:] - asum[:-n]
    return asum[n - 1:] / n
a = [3,5,7,2,8,10,11,65,72,81,99,100,150]
a1 = np.array(a)
np.array(moving_average(a1,n=3)).round(2)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])